In [30]:
import numpy as np
# Transponer un vector o matriz, es cambiar las filas por columnas

In [31]:
escalar = 6.3256
vector = np.array([1,2,3,4])
matriz = np.array([[14,24],[45,55],[67,69]])
tensor = np.array([
    [[14,24,34, 20],[45,55,56, 20],[67,68,79, 50]],
    [[100,101,102, 12],[103,104,105,23],[160,170,180,23]],
    [[190,200,210,50], [220,230,204,34], [255,227,238,55]]
])

In [32]:
# escalar_t = escalar.T -> AttributeError
# Por definición un escalar no tiene ni filas ni columnas

In [33]:
print(vector)


[1 2 3 4]


In [34]:
vector_t = vector.T
print(vector_t)

[1 2 3 4]


In [35]:
print(matriz)

[[14 24]
 [45 55]
 [67 69]]


In [36]:
matriz_t = matriz.T
print(matriz_t)

[[14 45 67]
 [24 55 69]]


In [37]:
print(tensor)


[[[ 14  24  34  20]
  [ 45  55  56  20]
  [ 67  68  79  50]]

 [[100 101 102  12]
  [103 104 105  23]
  [160 170 180  23]]

 [[190 200 210  50]
  [220 230 204  34]
  [255 227 238  55]]]


In [38]:
tensor_t = tensor.T
print(tensor_t)

[[[ 14 100 190]
  [ 45 103 220]
  [ 67 160 255]]

 [[ 24 101 200]
  [ 55 104 230]
  [ 68 170 227]]

 [[ 34 102 210]
  [ 56 105 204]
  [ 79 180 238]]

 [[ 20  12  50]
  [ 20  23  34]
  [ 50  23  55]]]


In [40]:
matriz_t_t = matriz_t.T
print(matriz_t_t)
# Retorna la matriz original

[[14 24]
 [45 55]
 [67 69]]


In [41]:
# La suma de matrices se puede dar cuando las matrices tienen la misma cantidad de filas y columnas, o si se suma con un escalar
# En las siguientes lecciones se enseña broadcasting, para sumar distintas filas y columnas

In [43]:
A = matriz
B = matriz_t
# Marca error, dado que no tienen la misma cantidad de filas y columnas
# C = A + B -> ValueError                                

In [45]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[6,5],[4,3],[2,1]])
C = A + B
print(A)
print(B)
print(C)

[[1 2]
 [3 4]
 [5 6]]
[[6 5]
 [4 3]
 [2 1]]
[[7 7]
 [7 7]
 [7 7]]


In [46]:
D = matriz + escalar 
print(D)

[[20.3256 30.3256]
 [51.3256 61.3256]
 [73.3256 75.3256]]
