In [1]:
import numpy as np

In [2]:
escalar = False
vector = np.array([1,2,3,4])
matriz = np.array([[14,24,34],[45,55,56],[67,68,79]])
tensor = np.array([
    [[14,24,34],[45,55,56],[67,68,79]],
    [[100,101,102],[103,104,105],[160,170,180]],
    [[190,200,210], [220,230,204], [255,227,238]]
])


In [3]:
#.shape retorna la dimensión de nuestros objetos

In [4]:
# escalar.shape
# False, un escalar no tiene este atributo
# .size() -> Retorna la cantidad total de elementos

In [5]:
print(escalar)

False


In [6]:
print(vector)
print(vector.size)
vector.shape
# (4,)

[1 2 3 4]
4


(4,)

In [7]:
print(matriz)
print(matriz.size)

matriz.shape
# (3, 3)

[[14 24 34]
 [45 55 56]
 [67 68 79]]
9


(3, 3)

In [8]:
print(tensor)
print(tensor.size)

tensor.shape
# (3, 3, 3)

[[[ 14  24  34]
  [ 45  55  56]
  [ 67  68  79]]

 [[100 101 102]
  [103 104 105]
  [160 170 180]]

 [[190 200 210]
  [220 230 204]
  [255 227 238]]]
27


(3, 3, 3)