In [10]:
# Broadcasting: Extiende el elemento de menor dimensión, hasta completar o igualar
# el de menor dimensión.

In [ ]:
import numpy as np

In [11]:
escalar = 5.6532
vector = np.array([3,4,5])
matriz = np.array([[1,2],[3,4],[5,6]])

In [12]:
# A = vector + matriz -> No será posible

In [13]:
A = matriz.T + vector

In [14]:
print(A) 

[[ 4  7 10]
 [ 5  8 11]]


In [15]:
C = matriz + 42

In [16]:
print(C)

[[43 44]
 [45 46]
 [47 48]]


In [17]:
D = matriz + np.array([[42],[42],[42]])

In [18]:
print(D)

[[43 44]
 [45 46]
 [47 48]]


In [19]:
vector_n = np.array([1,2,3,4,5,])
matriz_n = np.array([
    [1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5],
])
suma_n = vector_n + matriz_n

print(suma_n)

[[ 2  4  6  8 10]
 [ 2  4  6  8 10]
 [ 2  4  6  8 10]
 [ 2  4  6  8 10]
 [ 2  4  6  8 10]]
